# Generated by Django 3.1.6 on 2021-02-14 04:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('marital_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('marital_status_desc', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'm_marital_status',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('religion_id', models.AutoField(primary_key=True, serialize=False)),
                ('religion_name', models.CharField(max_length=50, unique=True)),
                ('usr_crt', models.CharField(max_length=50)),
                ('usr_upd', models.CharField(max_length=50)),
                ('dtm_crt', models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 14, 11, 27, 17, 118228))),
                ('dtm_upd', models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 14, 11, 27, 17, 118228))),
            ],
            options={
                'db_table': 'm_religion',
            },
        ),
        migrations.CreateModel(
            name='DukcapilData',
            fields=[
                ('dukcapil_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('maiden_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukcapil.maritalstatus', to_field='marital_status_desc')),
                ('religion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukcapil.religion')),
            ],
            options={
                'db_table': 'm_dukcapil_data',
            },
        ),
    ]
