# Generated by Django 3.1.6 on 2021-02-09 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('marital_status_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('marital_status_desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'm_marital_status',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('religion_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('religion_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'm_religion',
            },
        ),
        migrations.CreateModel(
            name='DukcapilData',
            fields=[
                ('dukcapil_data_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nik', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('maiden_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('marital_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dukcapil.maritalstatus')),
                ('religion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dukcapil.religion')),
            ],
            options={
                'db_table': 'm_dukcapil_data',
            },
        ),
    ]
