# Generated by Django 3.1.6 on 2021-02-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukcapil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukcapildata',
            name='dukcapil_data_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='marital_status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='religion',
            name='religion_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
