# Generated by Django 3.1.6 on 2021-02-14 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dukcapil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='dtm_crt',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2021, 2, 14, 12, 2, 17, 5383)),
        ),
        migrations.AlterField(
            model_name='religion',
            name='dtm_upd',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2021, 2, 14, 12, 2, 17, 5383)),
        ),
        migrations.CreateModel(
            name='DukcapilCheckResult',
            fields=[
                ('t_dukcpil_check_result', models.AutoField(primary_key=True, serialize=False)),
                ('check_dtm', models.DateTimeField(auto_now_add=True)),
                ('check_status', models.CharField(choices=[('Found', 'Found'), ('Not Found', 'Not Found')], max_length=20)),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukcapil.dukcapildata', to_field='nik')),
            ],
        ),
    ]
