# Generated by Django 3.1.6 on 2021-02-14 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukcapil', '0002_auto_20210214_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukcapilcheckresult',
            name='nik',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='religion',
            name='dtm_crt',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2021, 2, 14, 14, 32, 38, 375777)),
        ),
        migrations.AlterField(
            model_name='religion',
            name='dtm_upd',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2021, 2, 14, 14, 32, 38, 375777)),
        ),
    ]
