# Generated by Django 3.1.6 on 2021-02-09 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dukcapil', '0002_auto_20210209_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukcapildata',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukcapil.maritalstatus'),
        ),
        migrations.AlterField(
            model_name='dukcapildata',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukcapil.religion'),
        ),
    ]
